// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicShop.Models;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace MusicShop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200328231242_ChangedCartIdTypetostring")]
    partial class ChangedCartIdTypetostring
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("MusicShop.Models.Cart", b =>
                {
                    b.Property<string>("CartId")
                        .HasColumnType("text");

                    b.HasKey("CartId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("MusicShop.Models.CartItem", b =>
                {
                    b.Property<int>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CartId")
                        .HasColumnType("text");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("CartItemId");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("MusicShop.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CategoryDescription")
                        .HasColumnType("text");

                    b.Property<string>("CategoryName")
                        .HasColumnType("text");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryDescription = "Vintage and modern electric guitars",
                            CategoryName = "Electric Guitars"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryDescription = "Powerful and professional electric guitar amplifiers",
                            CategoryName = "Electric Guitar Amplifiers"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryDescription = "4-string and 5-string electric basses",
                            CategoryName = "Electric Basses"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryDescription = "Loud and mobile electric bass amplifiers",
                            CategoryName = "Bass Amplifiers"
                        });
                });

            modelBuilder.Entity("MusicShop.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AmountInStock")
                        .HasColumnType("integer");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("ImageThumbnailUrl")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("InStock")
                        .HasColumnType("boolean");

                    b.Property<string>("LongDescription")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("ProductName")
                        .HasColumnType("text");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("text");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 8,
                            AmountInStock = 0,
                            CategoryId = 4,
                            ImageThumbnailUrl = "https://thumbs.static-thomann.de/thumb/thumb150x150/pics/prod/482991.jpg",
                            ImageUrl = "https://bdbo2.thomann.de/thumb/bdb2500/pics/bdbo/14778071.jpg",
                            InStock = false,
                            LongDescription = "Fender AM Vintage 70th Anniversary Broadcaster BGB, electric guitar, ash body, maple neck, 50s Broadcaster 'U' shape, maple fretboard, 7.25' radius, 21x vintage tall style frets, 41,4mm bone nut, 648mm scale, 2x customshop handwound ,50-,51 blackguard single-coil pickups, Single Line 'Fender Deluxe' vintage style tuning keys, original vintage-style Tele, Bridge with 3 brass saddles, finish: Blackguard Blonde,New Fender Flash Coat Lacquer, incl vintage tweed case",
                            Price = 2199m,
                            ProductName = "Fender 70th Anniversary Broadcaster",
                            ShortDescription = "Fender AM Vintage 70th Anniversary Broadcaster BGB, electric guitar, ash body, maple neck, 50s Broadcaster 'U' shape."
                        },
                        new
                        {
                            ProductId = 1,
                            AmountInStock = 10,
                            CategoryId = 4,
                            ImageThumbnailUrl = "https://thumbs.static-thomann.de/thumb/thumb150x150/pics/prod/474509.jpg",
                            ImageUrl = "https://images.static-thomann.de/pics/prod/474509.jpg",
                            InStock = true,
                            LongDescription = "Cream binding,Neck: Mahogany (Swietenia macrophylla),Fretboard: Rosewood (Dalbergia Latifolia)'C'shaped neck profile,22 Medium frets,2 Gibson mini humbuckers,3-Way toggle switch,2 Volume controls, 2 tone controls,Tune-o-matic bridge and aluminium stoptail,Case included,Colour: Black,Made in USA",
                            Price = 1598m,
                            ProductName = " Gibson Les Paul Deluxe Ebony ",
                            ShortDescription = "Gibson Les Paul Deluxe Ebony. Body: Mahogany (Swietenia macrophylla). "
                        },
                        new
                        {
                            ProductId = 2,
                            AmountInStock = 0,
                            CategoryId = 1,
                            ImageThumbnailUrl = "https://thumbs.static-thomann.de/thumb/thumb150x150/pics/prod/422013.jpg",
                            ImageUrl = "https://bdbo2.thomann.de/thumb/bdb2500/pics/bdbo/12894607.jpg",
                            InStock = false,
                            LongDescription = "All Tube Combo Amp for Electric Guitar, Reissue series - authentic DSL sound Power: 40W 2 footswitchable channels with classic gain and ultra gain Assembly: 12' Celestion V Type loudspeaker Preamp tubes: 4 x ECC83 Power tubes: 2 x EL34 Independent volume and gain controls for both channels Clean and Crunch Modes in the Classic Gain Channel Lead 1 and Lead 2 modes in the Ultra Gain channel Classic sound control with bass, middle and treble Presence control Tone - shift circuit Variable resonance control Pentode - / triode switch Digital reverb independent for each channel Speaker outputs: 2 x 16 ohms, 1 x 8 ohms and 1 x 16 ohms Includes double footswitch(channel selection and reverb on / off",
                            Price = 649m,
                            ProductName = "Marshall DSL40CR ",
                            ShortDescription = "All Tube Combo Amp for Electric Guitar"
                        },
                        new
                        {
                            ProductId = 3,
                            AmountInStock = 10,
                            CategoryId = 1,
                            ImageThumbnailUrl = "https://thumbs.static-thomann.de/thumb/thumb150x150/pics/prod/189900.jpg",
                            ImageUrl = "https://bdbo2.thomann.de/thumb/bdb2500/pics/bdbo/10203745.jpg",
                            InStock = true,
                            LongDescription = "The Fender Blues Junior is the bigger brother of the Junior Pro. It packs just 15 W of power, but this is absolutely sufficient for many applications. The Blues Junior offers spring reverb and a 3-band EQ, as well as gain and master volume, meaning the sound can also be quietly distorted. Of course, it sounds better when the master is open, at which point you will realise in amazement how loud 15 W can actually be. With its 12' speaker, the amp has enough pressure to fill small clubs with sound. The name says it all: the Blues Junior is an excellent amp (not only, but especially) for blues, where the guitar can be a little ",
                            Price = 633m,
                            ProductName = "Fender Blues Junior Lacquered Tweed",
                            ShortDescription = "The Fender Blues Junior is the bigger brother of the Junior Pro. It packs just 15 W of power, but this is absolutely sufficient for many applications."
                        },
                        new
                        {
                            ProductId = 4,
                            AmountInStock = 10,
                            CategoryId = 2,
                            ImageThumbnailUrl = "https://thumbs.static-thomann.de/thumb/thumb150x150/pics/prod/456888.jpg",
                            ImageUrl = "https://images.static-thomann.de/pics/prod/456888.jpg",
                            InStock = true,
                            LongDescription = "Duff McKagan (Guns'n' Roses) artist series model Body: Alder Bolt-on neck: Maple Fretboard: Rosewood Pearloid block fretboard inlays Neck profile: Modern C Fretboard radius: 241.3 mm (9.5') Nut width: 41.3 mm (1.63') 20 Medium jumbo frets Three-layer Black / White / Black pickguard Pickup: Seymour Duncan STKJ2B Jazz Bass single coil and split coil 1 Volume control and 1 TBX Tone control 4-Saddle pure vintage 70s bridge with single groove saddles Nickel / Chrome hardware Fender '70s vintage style stamped Open-Gear tuners with Hipshot Bass Xtender 'Drop D' on the E-string Ex-factory stringing: Fender USA Bass 7250M NPS .045 - .105 Colour: White pearl, Gig bag included.",
                            Price = 1299m,
                            ProductName = "Fender Duff McKagan DLX P Bass RW WPL",
                            ShortDescription = "Fender Duff McKagan DLX P Bass RW WPL, Duff McKagan (Guns'n' Roses) artist series model"
                        },
                        new
                        {
                            ProductId = 5,
                            AmountInStock = 10,
                            CategoryId = 2,
                            ImageThumbnailUrl = "https://thumbs.static-thomann.de/thumb/thumb150x150/pics/prod/439272.jpg",
                            ImageUrl = "https://bdbo2.thomann.de/thumb/bdb2500/pics/bdbo/13199766.jpg",
                            InStock = true,
                            LongDescription = "Body: Alder, Maple neck,Fretboard: Maple,Matte neck finish,20 Frets, Nut width: 41.3 mm,Scale: 864 mm,Pickups: New Player AlNiCo V Precision Split single coil,Volume knob and tone knob,Standard open gear machine heads,Ex-factory stringing: Fender 7250M .045 - .105 (article nr 142933),Colour: Buttercream.",
                            Price = 659m,
                            ProductName = "Fender Player Series P-Bass MN BCR",
                            ShortDescription = "Fender Player Series P-Bass MN BCR, Body: Alder, Maple neck."
                        },
                        new
                        {
                            ProductId = 6,
                            AmountInStock = 10,
                            CategoryId = 3,
                            ImageThumbnailUrl = "https://thumbs.static-thomann.de/thumb/thumb150x150/pics/prod/380275.jpg",
                            ImageUrl = "https://bdbo2.thomann.de/thumb/bdb2500/pics/bdbo/10880172.jpg",
                            InStock = true,
                            LongDescription = "Power: 300W at 4Ω,Class A/B,Equipped with: 1x 15 Eminence neodymium speaker,Speaker Twist speaker connector,Controls: Master, bass, middle, treble, blend, drive,Balanced XLR out,Special feature: Low frequencies of the bass signal remain undistorted, mid and high frequencies are harmonically enriched with additional overtones by a separate drive circuit (controllable by Blend control),Bi-amp switchable by foot switch,Dimensions (W x H x D): 55 x 68 x 35 cm, Weight: 29.65 kg.",
                            Price = 1179m,
                            ProductName = "Orange OB1-300 Combo",
                            ShortDescription = "Bi-Amp Bass Combo"
                        },
                        new
                        {
                            ProductId = 7,
                            AmountInStock = 0,
                            CategoryId = 3,
                            ImageThumbnailUrl = "https://thumbs.static-thomann.de/thumb/thumb150x150/pics/prod/470477.jpg",
                            ImageUrl = "https://bdbo2.thomann.de/thumb/bdb2500/pics/bdbo/14519669.jpg",
                            InStock = false,
                            LongDescription = "Power: 100 W, Equipped with: 1x 12' Ashdown Speaker, Tube emulation, Active and passive input, 5-Band EQ, Shape switch, DI Out(XLR), Overdrive control, FX loop, Headphone output, Line in, Footswitch connection(Drive), Dimensions(W x D x H): 41.4 x 37.8 x 47.2 cm, Weight: 10.3 kg.",
                            Price = 299m,
                            ProductName = "Ashdown Studio 12",
                            ShortDescription = "Ashdown Studio 12, Power: 100 W, Equipped with: 1x 12' Ashdown Speaker"
                        });
                });

            modelBuilder.Entity("MusicShop.Models.CartItem", b =>
                {
                    b.HasOne("MusicShop.Models.Cart", null)
                        .WithMany("CartItems")
                        .HasForeignKey("CartId");

                    b.HasOne("MusicShop.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MusicShop.Models.Product", b =>
                {
                    b.HasOne("MusicShop.Models.Category", "Category")
                        .WithMany("ProductList")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
